### ISSUE TITLE
How to customize the data source?

### ISSUE THREAD

**Issue by shengzhou1216** [AI4Finance-Foundation/FinRL-Meta#238]
How to customize the data source? or How to use "User-imported Datasets" as described in the following figure

![](https://finrl.readthedocs.io/en/latest/_images/finrl_framework.png)

**Comment by XiaoYangLiu-FinRL** [comment]
Would you like to check the data processor at: https://github.com/AI4Finance-Foundation/FinRL-Meta/tree/master/meta/data_processors

**Comment by ZiyiXia** [comment]
Yeah, customize a `data_processor` class should be the most straightforward way. Basically your main work will be in the `download_data()` function, and make sure that the dataframe you generated by your data is in the correct form that `clean_data()`, `add_technical_indicator(), etc. could work with. Otherwise you need to modify those functions specifically.

**Comment by shengzhou1216** [comment]
thx. :+1:
