### ISSUE TITLE
Great vision for this repo, but too many bugs for now, none of those demo ipython notebook runs without bugs on my computer 

### ISSUE THREAD

**Issue by meanmee** [AI4Finance-Foundation/FinRL-Meta#98]

**Comment by XiaoYangLiu-FinRL** [comment]
At this moment, this repo is at the beginning stage. We are aiming for standarding our data processing workflow as a team…sharing the codes we use, while supporting FinRL. It is OK to have so many bugs, since it is not the target tool but a byproduct, as long as the codes are useful and are improving continuously.
